<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_username</name>
   <tag></tag>
   <elementGuidId>a3af52cd-00c3-4d1a-8407-6d062754b7fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#usernameText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='usernameText']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>41e53ca8-f0fb-4643-92fe-2bebb79a002f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>434e8723-189a-421a-a0cd-5465cf9ccfe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>usernameText</value>
      <webElementGuid>9c4d7c2e-88a8-4a36-a331-9793e593baf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>a3eaacb0-edfd-4614-9e7d-722f597eca58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;usernameText&quot;)</value>
      <webElementGuid>a1709171-9b63-48fc-8f50-4d4fe07a3a54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='usernameText']</value>
      <webElementGuid>5c5d8ec0-4999-4619-b7c8-6d4085a62419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2530e2bf-beb2-4044-8da6-949ccc2099a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'usernameText' and @name = 'username']</value>
      <webElementGuid>da4ebd4c-477a-45db-a4f9-ec11952f38b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
