<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Login_comment-button</name>
   <tag></tag>
   <elementGuidId>c15cf838-3652-42e5-8e1b-44f9420c46d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Comment']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.comment-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a:nth-child(2) >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>423d48c9-8972-4c8a-9a9e-c01b86b4e938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>comment-button</value>
      <webElementGuid>04ea8f39-103c-45e9-bb06-b4843460fe83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/comment-regular.svg</value>
      <webElementGuid>4405d1c0-52fc-4e0e-aad8-1522ed3da80b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Comment</value>
      <webElementGuid>018ee067-65a9-44e8-8990-d80497361c06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/main[@class=&quot;pb-3&quot;]/div[1]/div[@class=&quot;post-container&quot;]/div[@class=&quot;bottom-section&quot;]/div[@class=&quot;right-elements&quot;]/a[2]/img[@class=&quot;comment-button&quot;]</value>
      <webElementGuid>e1cdb906-1fe8-4a8a-9cd6-30d2635b6ced</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Comment']</value>
      <webElementGuid>b2055d6f-c32d-43b8-a5d2-4f8481057e93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/img</value>
      <webElementGuid>2d09b246-28e6-4e7b-9408-6598abcb975b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/comment-regular.svg' and @alt = 'Comment']</value>
      <webElementGuid>2875be30-ed1c-40a2-b747-cadaa593abec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
