<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Typing_messageInput</name>
   <tag></tag>
   <elementGuidId>138e1ee6-e1a6-4253-8afd-ab0f5f704fb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#messageInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='messageInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Type a message...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>68d64af4-6af0-4612-bd8f-07ee030c5d15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a032d544-eaa7-44d9-8953-4b55d67b780e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>messageInput</value>
      <webElementGuid>07ef5c43-7a17-4f17-8543-dd780238f7d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type a message...</value>
      <webElementGuid>6b6fced7-f65b-44d6-a86a-cf4c951bea94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;messageInput&quot;)</value>
      <webElementGuid>dd2e897f-dcd0-4bac-8190-8bbe78ee60ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='messageInput']</value>
      <webElementGuid>dda9f566-0614-440a-becd-c44144083d1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>67560831-4b79-4198-8b89-3be31c4773b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'messageInput' and @placeholder = 'Type a message...']</value>
      <webElementGuid>86e0dc15-3648-423f-a1de-6e250902435c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
