<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Stank</name>
   <tag></tag>
   <elementGuidId>21fbc62e-bc27-424f-952c-d51bf72dfb3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.convo_list > li</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@onclick='selectConvo(1)']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Stank&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>8454120a-2dee-45f6-8508-583ae82d377c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>selectConvo(1)</value>
      <webElementGuid>89a3e8c7-2cae-4589-99d7-76309c29a8cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Stank</value>
      <webElementGuid>00431ad2-f896-41b0-83b9-c509428cb924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/main[@class=&quot;pb-3&quot;]/div[@class=&quot;side_bar&quot;]/ul[@class=&quot;convo_list&quot;]/li[1]</value>
      <webElementGuid>f0fd6c4b-98ca-4a0a-8202-4a0a36802ff8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@onclick='selectConvo(1)']</value>
      <webElementGuid>3bc919a3-4b52-4e8d-a6f0-626998a536a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Conversations'])[1]/following::li[1]</value>
      <webElementGuid>23b8bac9-8a6e-42a6-b804-3ab554c7cc60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AstroMessage'])[2]/following::li[1]</value>
      <webElementGuid>dc6e98d0-6d54-4f0e-bbb5-43d2c43ad673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jschulz'])[1]/preceding::li[1]</value>
      <webElementGuid>9365e642-f05d-46d2-9950-aed813a24e4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nmasquiteo'])[1]/preceding::li[2]</value>
      <webElementGuid>f5235547-f1a2-43d6-bf6b-83b2beb977d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Stank']/parent::*</value>
      <webElementGuid>0c10378d-1ffd-4b05-8418-f554b7c82691</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/ul/li</value>
      <webElementGuid>55b6ea8b-8de4-474a-b763-aa029ea4163c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Stank' or . = 'Stank')]</value>
      <webElementGuid>f74d73ac-c04f-4038-9717-a608a58d44ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
