<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Typing_messageInput</name>
   <tag></tag>
   <elementGuidId>6446b43f-83d2-42c2-b434-6526e58d2702</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#messageInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='messageInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Type a message...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f03610bb-e294-4404-906c-7afffd486740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5e375c38-3a5d-410f-a946-05b283d97fc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>messageInput</value>
      <webElementGuid>d3e7b64b-03cc-434b-88aa-2f6404bb583a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type a message...</value>
      <webElementGuid>3c053313-0475-475a-a599-556e23390aa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;messageInput&quot;)</value>
      <webElementGuid>1b2e3d5a-fb9b-45b0-84ac-a2d3a68ab050</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='messageInput']</value>
      <webElementGuid>55ed6e47-5e88-428f-ac5b-e8ba13779a3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>1c26a305-0edf-4561-8241-edf0ff6f024b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'messageInput' and @placeholder = 'Type a message...']</value>
      <webElementGuid>61e7fb73-bb69-4d09-9430-2095283a2ff9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
