<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Stank</name>
   <tag></tag>
   <elementGuidId>cb4f2c8a-8776-49d2-bfe4-a69b2e7a0c90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.convo_list > li</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@onclick='selectConvo(1)']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Stank&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>18836488-c5ef-4a86-b2c5-4fd62a511173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>selectConvo(1)</value>
      <webElementGuid>1cca50dd-b798-4926-85dd-d648b6a08440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Stank</value>
      <webElementGuid>f5b76dbf-ecb1-451f-8e2d-7d1c0133c2a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/main[@class=&quot;pb-3&quot;]/div[@class=&quot;side_bar&quot;]/ul[@class=&quot;convo_list&quot;]/li[1]</value>
      <webElementGuid>b3b9e225-35f6-40c4-ae07-b3f7fe2aa7fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@onclick='selectConvo(1)']</value>
      <webElementGuid>1cbf81d5-a66c-4f07-89e0-4034378fe7c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Conversations'])[1]/following::li[1]</value>
      <webElementGuid>36943abe-5bfb-472b-b3aa-28dc5781a0c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AstroMessage'])[2]/following::li[1]</value>
      <webElementGuid>983711ad-f03a-40a1-9cc8-00aca4bd6c5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jschulz'])[1]/preceding::li[1]</value>
      <webElementGuid>3e43f342-0791-4d8e-b7f0-84905ae9e2b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nmasquiteo'])[1]/preceding::li[2]</value>
      <webElementGuid>4b0901ab-e687-4479-b32f-41cbac7c6dca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Stank']/parent::*</value>
      <webElementGuid>e742f20d-7b45-4a20-aa55-0e83b457585d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/ul/li</value>
      <webElementGuid>5dc868d9-d7fb-48ab-a962-23d73a7686f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Stank' or . = 'Stank')]</value>
      <webElementGuid>f161664d-3a36-4500-a3a4-649759c29b2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
