<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_username</name>
   <tag></tag>
   <elementGuidId>2c80de8c-a813-46d0-a05c-90090bd82f3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#usernameText</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='usernameText']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>69d8a6c3-6871-4929-9805-89c95b1ba179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2fdccf63-df68-4ac7-9e7e-c9254fd06c71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>usernameText</value>
      <webElementGuid>00ceb936-e49c-4c53-a3f8-bb9c8d857de8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>034a575d-c232-4cb8-8405-98e8590baa25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;usernameText&quot;)</value>
      <webElementGuid>fd4e4f8b-e7e0-4a6f-9814-65e5fe10a91b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='usernameText']</value>
      <webElementGuid>4ed8eadb-3e44-4551-9a1c-6762abe2a0cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>16b7e0d6-14a7-488a-8e0f-d8dd44190451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'usernameText' and @name = 'username']</value>
      <webElementGuid>d148212b-b0a2-4426-b397-dc882a38b375</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
